import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/sidebar";
import { ToastContainer } from "react-toastify";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${inter.className} w-full h-full antialiased flex`}>
        <Sidebar />
        <div className="p-8 bg-zinc-100 h-full w-full">{children}</div>
        <ToastContainer theme="light" hideProgressBar />
      </body>
    </html>
  );
}
